### ISSUE TITLE
Client Side Plans

### ISSUE THREAD

**Issue by gricey432** [eoranged/squash#11]
What are the plans for the client side? I am locally about halfway through a rewrite of RQ-Dashboard in React but would be keen to abandon that and contrib to this project instead.

Mentioned here: https://github.com/eoranged/rq-dashboard/issues/91

**Comment by eoranged** [comment]
The project in whole needs complete redesign (not only in terms of the looks, but in terms of functionality and data representation).
I'm not sure that React is a good choice in this case, because It adds extra bunch of build-time requirements (nodejs with tons of packages), but I'm open for discussion. 
If you are planning to change only web UI without change of what actually is displayed, then It's better to do It in scope of RQ dashboard since this project is a long-term idea and will not be of any use for a couple of months at least.

Also, If you want to create UI with React, I believe It will be best to add It as option. At least at the beginning. If you need help with this, please let me know and we'll discuss the process.
This way you can start adding new functionality will smaller portions (which is also easier to review) and users will be able to install dashboard with minimal list of dependencies if they want to.

Once your version of UI will be ready and will cover all use-cases of current web interface, we can make It default for docker images and include prebuilt version to PyPI package.

For *squash*, I'm currently drawing bazzilion of potential UI options. Once I'll come up with something useful, there will be a minimalist version (most likely very crud and simple HTML with tables in IE6 style), which can be turned to something better-looking and reactive before being announced to end users.

Main goal for this project is to make something rather different in terms of UI and data representation, but I'm currently unable to explain It in detail to someone else to take over. So If you want to join this project you'll need to wait a little bit :)
